#Requires -Version 7.4

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("Cloud", "SelfHosted")]
    [string]$Mode
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "common.ps1")

$marker = "# Generated by Marufia select-client-backend.ps1"
$projectRoot = Split-Path -Parent $script:MarufiaServerRoot
$clientEnvironmentPath = Join-Path $projectRoot ".env.local"

try {
    if (Test-Path -LiteralPath $clientEnvironmentPath -PathType Leaf) {
        $firstLine = [System.IO.File]::ReadLines($clientEnvironmentPath) | Select-Object -First 1
        if ($firstLine -ne $marker) {
            throw ".env.local pertence ao usuário e não será sobrescrito. Remova ou renomeie esse arquivo manualmente."
        }
    }

    if ($Mode -eq "Cloud") {
        if (Test-Path -LiteralPath $clientEnvironmentPath -PathType Leaf) {
            Remove-Item -LiteralPath $clientEnvironmentPath -Force
        }
        Write-MarufiaMessage -Level INFO -Message "Cliente configurado para o Supabase Cloud pelo perfil versionado de fallback."
        return
    }

    Assert-MarufiaEnvironment
    $environment = Get-MarufiaEnvironmentMap
    $hostname = ConvertTo-MarufiaPublicHostname -Value $environment["CLOUDFLARE_TUNNEL_HOSTNAME"]
    $expectedUrl = "https://$hostname"
    if ($environment["MARUFIA_PUBLIC_URL"].TrimEnd("/") -ne $expectedUrl) {
        throw "O domínio self-hosted ainda não está alinhado no servidor."
    }
    $publishableKey = $environment["SUPABASE_PUBLISHABLE_KEY"].Trim()
    if (-not $publishableKey.StartsWith("sb_publishable_") -or $publishableKey -match "[\r\n]") {
        throw "A chave pública do cliente é inválida. Nenhuma configuração foi escrita."
    }
    $siteUrl = ([System.Uri]::new($environment["SITE_URL"])).GetLeftPart([System.UriPartial]::Authority).TrimEnd("/")
    $lines = @(
        $marker,
        "MARUFIA_BUILD_ENV=production",
        "MARUFIA_BACKEND_MODE=selfhosted",
        "SUPABASE_URL=$expectedUrl",
        "SUPABASE_PUBLISHABLE_KEY=$publishableKey",
        "MARUFIA_SITE_URL=$siteUrl"
    )
    $temporaryPath = "$clientEnvironmentPath.$PID.tmp"
    try {
        [System.IO.File]::WriteAllLines($temporaryPath, $lines, [System.Text.UTF8Encoding]::new($false))
        Move-Item -LiteralPath $temporaryPath -Destination $clientEnvironmentPath -Force
    } finally {
        if (Test-Path -LiteralPath $temporaryPath) { Remove-Item -LiteralPath $temporaryPath -Force }
    }
    Write-MarufiaMessage -Level INFO -Message "Cliente selecionado para o Marufia Server sem incluir chaves administrativas."
} catch {
    Write-MarufiaMessage -Level ERROR -Message $_.Exception.Message
    exit 1
}
